version: "3.7"

services:
    node-red:
        image: nodered/node-red:latest
        network_mode: "host"
        environment:
            - TZ=EST5EDT
        volumes:
            - ./data-linked:/data
            - ../packages/node-red-contrib-hamlib:/data/node_modules/node-red-contrib-hamlib
